# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc 'Build a new version of the app'
  lane :build do |options|
    gradle_properties = {
      apiUrl: options[:apiUrl].nil? ? ENV['API_URL'] : options[:apiUrl],
      deploymentKey: ENV['DEPLOYMENT_KEY']
    }

    gradle(
      task: 'assemble',
      build_type: ENV['CONFIGURATION_TYPE'],
      properties: gradle_properties
    )
    # upload_to_play_store
  end
end
